version: '3'

networks:
  back_default:
    driver: bridge
services:
  angular-app:
    build:
      context: ../Front
    ports:
      - "4200:80"

  spring-boot-app:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - back_default
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: fly_delivery
     # MYSQL_USER: root
     # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back_default