  version: '3.8'
  
  services:
    
    mysql-db:
      image: mysql:latest
      environment:
        #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: menta
        MYSQL_DATABASE: fly_delivery
      ports:
        - "3306:3306"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount your initialization script
        - ./mysql-data:/var/lib/mysql
      command: --init-file=/docker-entrypoint-initdb.d/init.sql
    angular-app:
      build:
        context: ../Front
      ports:
        - "4200:80"
      depends_on:
        - mysql-db
        - spring-boot-app
  
    spring-boot-app:
      build:
        context: ./
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/fly_delivery
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: menta
        #SPRING_DATASOURCE_PASSWORD: 
      depends_on:
      - wait-for-mysql

    wait-for-mysql:
      image: alpine:latest
      command: /bin/sh -c "until nc -zv mysql-db 3306; do echo 'Waiting for MySQL to start'; sleep 1; done"